# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=0, verbose_name=((0, 'incomplete'), (1, 'open'), (2, 'in-progress'), (3, 'in-review'), (4, 'completed')))),
                ('issue_type', models.IntegerField(default=0, verbose_name=((0, '(NEW)'), (1, '(MOD)'), (2, '(BUG)')))),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
