# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.IntegerField(choices=[(0, '(NEW)'), (1, '(MOD)'), (2, '(BUG)')], default=0),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(0, 'incomplete'), (1, 'open'), (2, 'in-progress'), (3, 'in-review'), (4, 'completed')], default=0),
        ),
    ]
